Updated CD pipeline to support cross platform builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -44,7 +44,10 @@ jobs:
 
     Building:
         name: Building Job
-        runs-on: windows-latest
+        strategy:
+          matrix:
+            os: [ubuntu-latest, windows-latest, macos-latest]
+        runs-on: ${{ matrix.os }}
         needs: Linting
         steps:
             - name: Check out repository code
@@ -60,7 +63,8 @@ jobs:
                 python -m pip install --upgrade pip
                 pip install -r requirements.txt
 
-            - name: Build executable
+            - name: Build executable Windows
+              if: matrix.os == 'windows-latest'
               run: |
                 pyinstaller --onefile klogger.py
                 if ($LASTEXITCODE -ne 0) {
@@ -68,15 +72,38 @@ jobs:
                     exit 1
                 }
 
-            - name: Archive build artifacts
+            - name: Build executable Linux & Mac
+              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+              run: |
+                pyinstaller --onefile klogger.py
+                if [ $? -ne 0 ]; then
+                  echo "Build failed."
+                  exit 1
+                fi
+
+            - name: Archive build artifacts Windows
+              if: matrix.os == 'windows-latest'
               uses: actions/upload-artifact@v4
               with:
                 name: klogger
                 path: dist/klogger.exe
+                
+            - name: Archive build artifacts Linux & Mac
+              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+              uses: actions/upload-artifact@v4
+              with:
+                name: klogger
+                path: dist/klogger
 
             - name: Create GitHub Release Windows
-              if: startsWith(github.ref, 'refs/tags/')
+              if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
               uses: softprops/action-gh-release@v1
               with:
                 files: dist/klogger.exe
+
+            - name: Create GitHub Release Linux & Mac
+              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
+              uses: softprops/action-gh-release@v1
+              with:
+                files: dist/klogger
    
