Fixed name issue for cross platform builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -66,44 +66,45 @@ jobs:
             - name: Build executable Windows
               if: matrix.os == 'windows-latest'
               run: |
-                pyinstaller --onefile klogger.py
+                pyinstaller --onefile klogger.py --name klogger-windows.exe
                 if ($LASTEXITCODE -ne 0) {
                     Write-Host "Build failed."
                     exit 1
                 }
 
-            - name: Build executable Linux & Mac
-              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
+            - name: Build executable Linux
+              if: matrix.os == 'ubuntu-latest'
               run: |
-                pyinstaller --onefile klogger.py
+                pyinstaller --onefile klogger.py --name klogger-linux
                 if [ $? -ne 0 ]; then
                   echo "Build failed."
                   exit 1
                 fi
 
-            - name: Archive build artifacts Windows
-              if: matrix.os == 'windows-latest'
-              uses: actions/upload-artifact@v4
-              with:
-                name: klogger
-                path: dist/klogger.exe
-                
-            - name: Archive build artifacts Linux & Mac
-              if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
-              uses: actions/upload-artifact@v4
-              with:
-                name: klogger
-                path: dist/klogger
+            - name: Build executable Mac
+              if: matrix.os == 'macos-latest'
+              run: |
+                pyinstaller --onefile klogger.py --name klogger-mac
+                if [ $? -ne 0 ]; then
+                  echo "Build failed."
+                  exit 1
+                fi
 
             - name: Create GitHub Release Windows
-              if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'windows-latest'
+              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'windows-latest')
               uses: softprops/action-gh-release@v1
               with:
-                files: dist/klogger.exe
+                files: dist/klogger-windows.exe
 
-            - name: Create GitHub Release Linux & Mac
-              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
+            - name: Create GitHub Release Linux
+              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'ubuntu-latest')
               uses: softprops/action-gh-release@v1
               with:
-                files: dist/klogger
+                files: dist/klogger-linux
+
+            - name: Create GitHub Release Mac
+              if: startsWith(github.ref, 'refs/tags/') && (matrix.os == 'macos-latest')
+              uses: softprops/action-gh-release@v1
+              with:
+                files: dist/klogger-mac
    
